SSL_CERT_DIR="/home/kevinstampe/.aspnet/dev-certs/trust:/etc/ssl/certs"
FunctionAppHostPath="/home/kevinstampe/.npm_packages/lib/node_modules/azure-functions-core-tools/bin/func.dll"
DotnetExecutablePath="/home/kevinstampe/dotnet"
