general {
	lock_cmd = hyprlock
}

listener {
	timeout = 180
	on-timeout = hyprlock 
}

listener {
  timeout = 3000
  on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "off" })'
  on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "on" })'
}
